Refactor click
RedHatQE/ocp-addons-operators-cli pull request #115
Opened 2023-06-13 13:51 UTC by myakove

Change the way that we get addon/operator args.
We get it as dict which is easier to work on.

2023-06-13 16:27 UTC, rnetser requested changes

2023-06-13 16:27 UTC, rnetser commented on README.md
> +* `timeout=300`: timeout to wait for the operator/addon to be installed/uninstalled
```suggestion
* `timeout=300`: timeout in seconds to wait for the operator/addon to be installed/uninstalled
```

2023-06-13 16:27 UTC, rnetser commented on README.md
> +* `iib=/path/to/iib:123456`: Install the operator using the provided IIB
what about ns, target-namespaces etc?

2023-06-13 16:27 UTC, rnetser commented on README.md
>      addon \
```suggestion
    addons \
```

2023-06-13 16:27 UTC, rnetser commented on README.md
> +    -o 'name=rhods-operator;namespace=redhat-ods-operator' \
```suggestion
    -o 'name=rhods-operator;namespace=redhat-ods-operator;timeout=600' \
```

2023-06-13 16:27 UTC, rnetser commented on README.md
> +    -o 'name=servicemeshoperator' \
```suggestion
    -o 'name=servicemeshoperator;timeout=600' \
```

2023-06-14 09:50 UTC, myakove commented
/verified

2023-06-15 00:29 UTC, oharan2 approved these changes

2023-06-15 00:30 UTC, oharan2 commented
/lgtm

2023-06-15 06:08 UTC, myakove commented
/verified

2023-06-15 06:33 UTC, merged