WIP: Changed pyproject.toml
RedHatQE/ocp-addons-operators-cli pull request #83
Opened 2023-05-28 14:33 UTC by oharan2

Requiring that `openshift-cluster-management-python-wrapper` version is higher than `1.0.20` - 
Will be verified after [#51](https://github.com/RedHatQE/openshift-cluster-management-python-wrapper/pull/51) is merged and a new version will be released.

2023-05-29 13:20 UTC, myakove requested changes
Why app/addon_cmds/commands.py was changed?

2023-05-29 13:20 UTC, myakove commented on pyproject.toml
> +openshift-cluster-management-python-wrapper = "^1.0.20"
should be `1.0.21`

2023-05-29 21:37 UTC, oharan2 commented
/verified

2023-05-30 20:46 UTC, oharan2 commented
[pre-commit.ci](http://pre-commit.ci/) run

2023-05-31 06:54 UTC, rnetser requested changes
Please update PR title - should describe the PR (it goes to release notes)

2023-05-31 09:02 UTC, oharan2 commented
/verified

2023-05-31 12:45 UTC, myakove commented
/lgtm

2023-05-31 18:09 UTC, rnetser approved these changes

2023-05-31 18:10 UTC, merged

2023-06-01 08:59 UTC, myakove commented
/lgtm